"""add_email_settings_to_organization

Revision ID: 45e36fa59a2c
Revises: f027d672093e
Create Date: 2026-01-18 19:11:48.487562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e36fa59a2c'
down_revision: Union[str, None] = 'f027d672093e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('auto_send_threshold', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('manual_review_threshold', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('vip_auto_review', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('proactive_delay_notifications', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE organizations SET auto_send_threshold = 95 WHERE auto_send_threshold IS NULL")
    op.execute("UPDATE organizations SET manual_review_threshold = 70 WHERE manual_review_threshold IS NULL")
    op.execute("UPDATE organizations SET vip_auto_review = true WHERE vip_auto_review IS NULL")
    op.execute("UPDATE organizations SET proactive_delay_notifications = true WHERE proactive_delay_notifications IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'proactive_delay_notifications')
    op.drop_column('organizations', 'vip_auto_review')
    op.drop_column('organizations', 'manual_review_threshold')
    op.drop_column('organizations', 'auto_send_threshold')
    # ### end Alembic commands ###
