"""add_org_user_profile_fields

Revision ID: f027d672093e
Revises: 4d8c580098cf
Create Date: 2026-01-18 18:09:38.603626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f027d672093e'
down_revision: Union[str, None] = '4d8c580098cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types
    industry_type_enum = sa.Enum('FREIGHT_FORWARDER', 'CHA', 'EXPORTER', name='industrytype')
    organization_status_enum = sa.Enum('ACTIVE', 'SUSPENDED', name='organizationstatus')
    department_enum = sa.Enum('OPS', 'SALES', 'ADMIN', name='department')
    
    industry_type_enum.create(op.get_bind(), checkfirst=True)
    organization_status_enum.create(op.get_bind(), checkfirst=True)
    department_enum.create(op.get_bind(), checkfirst=True)
    
    # Add organization columns
    op.add_column('organizations', sa.Column('industry_type', industry_type_enum, nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=True, server_default='UTC'))
    op.add_column('organizations', sa.Column('default_currency', sa.String(length=10), nullable=True, server_default='USD'))
    op.add_column('organizations', sa.Column('status', organization_status_enum, nullable=False, server_default='ACTIVE'))
    op.add_column('organizations', sa.Column('emails_per_day_limit', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('ai_usage_limit', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_organizations_industry_type'), 'organizations', ['industry_type'], unique=False)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    
    # Update existing rows to have default status
    op.execute("UPDATE organizations SET status = 'ACTIVE' WHERE status IS NULL")
    
    # Add user profile columns
    op.add_column('user_profiles', sa.Column('department', department_enum, nullable=True))
    op.add_column('user_profiles', sa.Column('signature', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_profiles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_profiles_deleted_at'), 'user_profiles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_department'), 'user_profiles', ['department'], unique=False)
    op.create_index(op.f('ix_user_profiles_is_enabled'), 'user_profiles', ['is_enabled'], unique=False)
    
    # Update existing rows to have is_enabled = true
    op.execute("UPDATE user_profiles SET is_enabled = true WHERE is_enabled IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_is_enabled'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_department'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_deleted_at'), table_name='user_profiles')
    op.drop_column('user_profiles', 'deleted_at')
    op.drop_column('user_profiles', 'is_enabled')
    op.drop_column('user_profiles', 'signature')
    op.drop_column('user_profiles', 'department')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_industry_type'), table_name='organizations')
    op.drop_column('organizations', 'ai_usage_limit')
    op.drop_column('organizations', 'emails_per_day_limit')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'default_currency')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'industry_type')
    # ### end Alembic commands ###
