"""add_email_model

Revision ID: 0eb64449c67c
Revises: 3b0b85276dad
Create Date: 2026-01-18 12:24:21.852518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb64449c67c'
down_revision: Union[str, None] = '3b0b85276dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'emails',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
        sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
        sa.Column('subject', sa.String(length=1000), nullable=True),
        sa.Column('from_email', sa.String(length=500), nullable=True),
        sa.Column('to_email', sa.Text(), nullable=True),
        sa.Column('cc_email', sa.Text(), nullable=True),
        sa.Column('bcc_email', sa.Text(), nullable=True),
        sa.Column('snippet', sa.Text(), nullable=True),
        sa.Column('body_html', sa.Text(), nullable=True),
        sa.Column('body_plain', sa.Text(), nullable=True),
        sa.Column('date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('has_attachments', sa.Boolean(), nullable=False),
        sa.Column('attachment_count', sa.Integer(), nullable=False),
        sa.Column('is_sent', sa.Boolean(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('is_processed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_emails_gmail_thread_id'), 'emails', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_emails_from_email'), 'emails', ['from_email'], unique=False)
    op.create_index(op.f('ix_emails_is_read'), 'emails', ['is_read'], unique=False)
    op.create_index(op.f('ix_emails_is_processed'), 'emails', ['is_processed'], unique=False)
    op.create_index('idx_user_unread', 'emails', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_user_unprocessed', 'emails', ['user_id', 'is_processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_unprocessed', table_name='emails')
    op.drop_index('idx_user_unread', table_name='emails')
    op.drop_index(op.f('ix_emails_is_processed'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_read'), table_name='emails')
    op.drop_index(op.f('ix_emails_from_email'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
